api/urls.py
from django.urls import path
from .views import *

app_name = "app"

urlpatterns = [
    path('', home, name="home"),
    path("apis/", LyricsApiView, name="apis"),
    path("add-api/", AddLyricsAPI, name="add_lyrics_api"),
    path("update-api/<int:pk>/", EditLyricsAPI, name="edit_lyrics_api"),
    path("api/<int:pk>/", LyricsSingleApiView, name="sing_api"),
    path("delete-api/<int:pk>/", DeleteLyricsAPI, name="delete_lyrics_api"),
    path("search-api/", lyricsSearch, name="lyrics_search"),
    path('submit-succses/', SuccsesView.as_view(), name="succses"),
]   

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView , LogoutView
from api.views import SignUpView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("api.urls")),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path("signup/", SignUpView.as_view(), name="signup" )
]

api/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class MyUser(AbstractUser):
    is_organiser = models.BooleanField(default=False)
    is_agent = models.BooleanField(default=False)


class Lyrics(models.Model):
    author_id = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    artist = models.CharField(max_length=30)
    title = models.CharField(max_length=30)
    lyrics = models.TextField(max_length=7000)

    def __str__(self):
        return f"post by {self.author_id}"

api/views.py
from django.shortcuts import render, redirect, reverse
from api.models import *
from django.db.models import Q
from django.views import generic
from api.form import *
from api.serializer import *
#rest_framework
from rest_framework.response import Response
from rest_framework.decorators import api_view, permission_classes
from rest_framework import permissions, filters, generics


def home(request):
    return render(request, "pages/home.html")

# Lyrics API
@api_view(["GET"])
@permission_classes((permissions.AllowAny, ))
def LyricsApiView(request):
    lyrics = Lyrics.objects.all()
    serializer = LyricsAPI(lyrics, many=True)
    return Response(serializer.data)
# Lyrics Single API
@api_view(["GET"])
@permission_classes((permissions.AllowAny, ))
def LyricsSingleApiView(request, pk):
    lyrics = Lyrics.objects.get(id=pk)
    serializer = LyricsAPI(lyrics, many=False)
    return Response(serializer.data)

# Craete Lyrics API
@api_view(["POST"])
@permission_classes((permissions.AllowAny, ))
def AddLyricsAPI(request):
    serializer = LyricsAPI(data=request.data)
    if serializer.is_valid():
        serializer.save()
    return Response(serializer.data)

@api_view(["POST"])
@permission_classes((permissions.AllowAny, ))
def EditLyricsAPI(request, pk):
    lyrics = Lyrics.objects.get(id=pk)
    serializer = LyricsAPI(instance=lyrics,data=request.data)
    if serializer.is_valid():
        serializer.save()
    return Response(serializer.data)

@api_view(["DELETE"])
@permission_classes((permissions.AllowAny, ))
def DeleteLyricsAPI(request, pk):
    lyrics = Lyrics.objects.get(id=pk)
    lyrics.delete()
    return Response("o'chirdiz")

class LyricsSearch(generics.ListAPIView):
    queryset = Lyrics.objects.all()
    serializer_class = LyricsAPI
    filter_backends = [filters.SearchFilter]
    search_fields = ['artist', 'title']

lyricsSearch = LyricsSearch.as_view()

class SignUpView(generic.CreateView):
    template_name = 'registration/signup.html'
    form_class = SignUpForm

    def get_success_url(self):
        return reverse("login")

class SuccsesView(generic.TemplateView):
    template_name = "pages/succses.html"

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>hello</h1>
</body>
</html>

templates/layouts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    {% include 'includes/nav.html' %}
    {% block content %}

    {% endblock content %}

</body>
</html>

templates/pages/home.html
{% extends 'layouts/base.html' %}

{% block title %}Home{% endblock title %}
{% block content %}
<h1>bu haome page</h1>
{% endblock content %}

templates/pages/succses.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Succses</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>

<body oncontextmenu= "return false">
    <style>
        body {
            background-color: #000000;
            background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='100%25' height='100%25' viewBox='0 0 1600 800'%3E%3Cg %3E%3Cpolygon fill='%23220000' points='1600 160 0 460 0 350 1600 50'/%3E%3Cpolygon fill='%23440000' points='1600 260 0 560 0 450 1600 150'/%3E%3Cpolygon fill='%23660000' points='1600 360 0 660 0 550 1600 250'/%3E%3Cpolygon fill='%23880000' points='1600 460 0 760 0 650 1600 350'/%3E%3Cpolygon fill='%23A00' points='1600 800 0 800 0 750 1600 450'/%3E%3C/g%3E%3C/svg%3E");
            background-attachment: fixed;
            background-size: cover;
            display: grid;
            place-items: center;
            min-height: 100vh;
        }

        a {
            position: absolute;
            top: 70px;
            left: 180px;
            text-decoration: none;
            color: #fff;
            font-size: 2rem;
            padding: 5px 10px;
            border-radius: 5px;
            transition: 0.5s all;
        }

        a:hover {
            box-shadow: inset 0px -100px #fff;
            color: #330033;
        }
    </style>

    <div style="position: relative;">
        <h1 class="text-center text-light">Your Datas <span class="text-danger">successfully</span> Add</h1>
        <a href="{% url 'app:home' %}">Go Home</a>
    </div>
</body>

</html>